### ISSUE TITLE
cherrytree-future is outdated

### ISSUE THREAD

**Issue by dodona2** [funnelfiasco/copr-cherrytree#13]
please update cherrytree-future to the most recent version. See: https://github.com/giuspen/cherrytree/issues/774

**Comment by funnelfiasco** [comment]
Just finished building 0.0.1.20200503git1b8db2b-1. You may need to pass the `--refresh` flag to dnf to see the update depending on the age of your cache.

**Comment by dodona2** [comment]
got it. 

- It really loads fast, however needs some time for storing. 
- It still converts 22px hight codeboxes to 40px. 
- After changing some properties and saving the data it still sends a 'not responding' message box after hitting the 'terminate' button.
- Otherwise its pretty fast.
