### ISSUE TITLE
Please update Cherrytree future to the newest release

### ISSUE THREAD

**Issue by dodona2** [funnelfiasco/copr-cherrytree#14]
thanks a lot in advance

**Comment by funnelfiasco** [comment]
`cherrytree-future 0.0.1.20200505git26afcc6` is now available except for armhfp, which is still building.

**Comment by funnelfiasco** [comment]
armhfp builds failed, but they've never build correctly, so I'll ignore that for now and close this.

**Comment by dodona2** [comment]
there already is a new release.
