### ISSUE TITLE
Missing dependencies on Fedora 32

### ISSUE THREAD

**Issue by angelforest** [funnelfiasco/copr-cherrytree#2]
When I try to install cherrytree on Fedora 32, installation fails with the following error:
```
Error: 
 Problem: conflicting requests
  - nothing provides dbus-python needed by cherrytree-0.38.10-1.fc32.noarch
  - nothing provides python2-appindicator needed by cherrytree-0.38.10-1.fc32.noarch
```

**Comment by funnelfiasco** [comment]
Looks like some Python 2 cleanup took out our dependencies. I'll try to get those into my copr repo soon. In the meantime, you could try the [unofficial Flatpak](https://gitlab.com/rszibele/flatpak-cherrytree).

It seems like upstream is close to shipping the rewrite, so once that's available, I'll look at getting that into the official repos.

**Comment by funnelfiasco** [comment]
Fixing the dependency chain is making me very sad. I'm going to see if building the future version works any better.

**Comment by funnelfiasco** [comment]
Okay, there's now a `cherrytree-future` package in the repo for F31 and F32. I intentionally did not have it obsolete `cherrytree` because I want it to be an explicit choice for the user. You'll have to uninstall `cherrytree` before you install `cherrytree-future`.
