### ISSUE TITLE
Cherrytree does not show its own icon in GNOME Wayland

### ISSUE THREAD

**Issue by sergiomenoyo** [funnelfiasco/copr-cherrytree#20]
I'm able to start cherrytree after click on its icon on favorites tray but after that it doesn't show its icon.

With thunderbird had a pretty similar bug (https://groups.google.com/g/linux.debian.bugs.dist/c/avkFxvmt-bM?pli=1) but you can fix it because you have a /usr/share/applications/thunderbird.desktop.

I have installed cherrytree from snap in red hat 9.

Thank you very much.

**Comment by funnelfiasco** [comment]
> I have installed cherrytree from snap in red hat 9.

I don't provide Snaps or any other RHEL 9 builds in my copr repo. You'll want to [file this upstream](https://github.com/giuspen/cherrytree/issues).
