### ISSUE TITLE
Focus not working correctly? Shortcuts are applied to wrong window.

### ISSUE THREAD

**Issue by sklages** [funnelfiasco/copr-cherrytree#4]
When editing the content of a node, all keyboard shortcuts are applied to the tree window.

E.g. I am writing some text and want to delete a char with DEL, then cherrytree asks me if I am sure that I want to delete the node.

Or using SHIFT-ARROW-LRUP results in funnily moving notes ...

Idea what happens here?

Fedora 32, GNOME 3.36.1

**Comment by sklages** [comment]
When removing or altering keyboard shortcuts, it works just fine.

E.g. removing DEL from shortcut list (by selecting "no keyboard shortcut"), I can still use DEL when tree window has the focus for removing notes. And it works just as intended when editing text ..

Notes cannot be moved by mouse, is this intentional behaviour?

**Comment by funnelfiasco** [comment]
@sklages please file this [upstream](https://github.com/giuspen/cherrytree/issues). I can't help with development, just packaging.
