### ISSUE TITLE
package conflict Fedora 31(libappindicator)

### ISSUE THREAD

**Issue by dodona2** [funnelfiasco/copr-cherrytree#5]
see https://bugzilla.redhat.com/show_bug.cgi?id=1829163

cherrytree is my only app depending on libappindicator.

**Comment by funnelfiasco** [comment]
I can't do much about the libappindicator packaging error, but if you want you can remove `cherrytree` and install `cherrytree-future`. This is the C++ rewrite that upstream is working on. It's an alpha at this point, but I've been using it without issue so far.

**Comment by dodona2** [comment]
cherrytree-future works in F32. Nevertheless I add the F32 install error message.
