### ISSUE TITLE
Cannot install on Fedora 32

### ISSUE THREAD

**Issue by jpweiser** [funnelfiasco/copr-cherrytree#6]
Get the following when attempting to install on Fedora 32

```
 Problem: cannot install the best candidate for the job
  - nothing provides dbus-python needed by cherrytree-0.38.10-1.fc32.noarch
  - nothing provides python2-appindicator needed by cherrytree-0.38.10-1.fc32.noarch
```

**Comment by funnelfiasco** [comment]
Yeah, the Python2 retirement took out a lot of our dependencies. I tried packaging them, but it got a little out of hand.

For Fedora 32 and Rawhide, you can install `cherrytree-future` instead. It's the C++ rewrite that upstream is working on. It's an alpha right now, but I've been using it without trouble so far.

**Comment by jpweiser** [comment]
Thank you.`cherrytree-future` works to view my notes. Cool to see progress on the C++ rewrite as well.
