### ISSUE TITLE
Fedora 32: can't install cherrytree. conflicting requests

### ISSUE THREAD

**Issue by dodona2** [funnelfiasco/copr-cherrytree#9]
Description of problem:
can't install cherrytree. conflicting requests 

Version-Release number of selected component (if applicable):
Fedora 32
cherrytree 0.38.10-1.fc32.noarch

How reproducible:
dnf install cherrytree

Steps to Reproduce:
1.dnf install cherrytree
2.see error message
3.

Actual results:
Last metadata expiration check: 0:04:21 ago on Sat 02 May 2020 07:17:31 AM CEST.
Error: 
 Problem: conflicting requests
  - nothing provides dbus-python needed by cherrytree-0.38.10-1.fc32.noarch
  - nothing provides python2-appindicator needed by cherrytree-0.38.10-1.fc32.noarch
(try to add '--skip-broken' to skip uninstallable packages)

Expected results:
successful installetion

**Additional info:**
[https://bugzilla.redhat.com/show_bug.cgi?id=1830488](url)

**Comment by funnelfiasco** [comment]
Yes, this is why I started packaging cherrytree-future. The dependency chain that I would have to package in Fedora 32 is too much work. I will not be adding Fedora 32 support for the Python 2 version of Cherrytree.

**Comment by funnelfiasco** [comment]
I'm not sure why that shows in the repo at all, I'll see if I can remove it.

**Comment by echevemaster** [comment]
I think is because you have the explicit require of  python2-libappindicator here https://github.com/funnelfiasco/copr-cherrytree/blob/master/cherrytree.spec#L27

**Comment by funnelfiasco** [comment]
No, I mean cherrytree shouldn't be in the Fedora 32 repo. I've removed that build from COPR, since it shouldn't have been submitted in the first place.
